// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7lbhINXimUpNInLlKTab2x6Nrn68ZcWQ',
    appId: '1:30987375161:web:e65467b494200f8887b3e8',
    messagingSenderId: '30987375161',
    projectId: 'emart-55f7e',
    authDomain: 'emart-55f7e.firebaseapp.com',
    storageBucket: 'emart-55f7e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4gmDXXe_OkA9P1Dfi--kKD60wcny388',
    appId: '1:30987375161:android:a256c1c921b7b61487b3e8',
    messagingSenderId: '30987375161',
    projectId: 'emart-55f7e',
    storageBucket: 'emart-55f7e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4oHVcfGau3TMmTXs0zzJpLm9fqxq8VDA',
    appId: '1:30987375161:ios:79630388aba2602b87b3e8',
    messagingSenderId: '30987375161',
    projectId: 'emart-55f7e',
    storageBucket: 'emart-55f7e.firebasestorage.app',
    iosBundleId: 'com.example.emartApp',
  );
}
